services:
  - type: web
    name: nightcoreartmuseum-web
    env: ruby
    region: frankfurt # or oregon
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: myapp-db
    plan: free
    region: frankfurt # or oregon
