services:
  - type: web
    name: nightcoreartmuseum-web
    env: ruby
    region: frankfurt # or oregon
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: myapp-redis
          type: pserv
          property: hostport
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: myapp-db
    plan: free
    region: frankfurt # or oregon